//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: LevelTwoCommand.proto
// Note: requires additional types generated from: Command.proto
// Note: requires additional types generated from: Respond.proto
namespace hrvv
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Power")]
  public partial class Power : global::ProtoBuf.IExtensible
  {
    public Power() {}
    
    private int _readpower;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"readpower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int readpower
    {
      get { return _readpower; }
      set { _readpower = value; }
    }
    private int _writepower;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"writepower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int writepower
    {
      get { return _writepower; }
      set { _writepower = value; }
    }
    private bool _loop;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"loop", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool loop
    {
      get { return _loop; }
      set { _loop = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Gpio")]
  public partial class Gpio : global::ProtoBuf.IExtensible
  {
    public Gpio() {}
    
    private int _gpio;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"gpio", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int gpio
    {
      get { return _gpio; }
      set { _gpio = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FrequencyPoint")]
  public partial class FrequencyPoint : global::ProtoBuf.IExtensible
  {
    public FrequencyPoint() {}
    
    private int _count;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _point = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(2, Name=@"point", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> point
    {
      get { return _point; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Carrier")]
  public partial class Carrier : global::ProtoBuf.IExtensible
  {
    public Carrier() {}
    
    private int _carrier;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"carrier", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int carrier
    {
      get { return _carrier; }
      set { _carrier = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Gen2")]
  public partial class Gen2 : global::ProtoBuf.IExtensible
  {
    public Gen2() {}
    
    private int _algorithm;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"algorithm", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int algorithm
    {
      get { return _algorithm; }
      set { _algorithm = value; }
    }
    private int _StartQ;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"StartQ", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int StartQ
    {
      get { return _StartQ; }
      set { _StartQ = value; }
    }
    private int _MinQ;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"MinQ", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int MinQ
    {
      get { return _MinQ; }
      set { _MinQ = value; }
    }
    private int _MaxQ;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"MaxQ", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int MaxQ
    {
      get { return _MaxQ; }
      set { _MaxQ = value; }
    }
    private int _select;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"select", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int select
    {
      get { return _select; }
      set { _select = value; }
    }
    private int _session;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"session", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int session
    {
      get { return _session; }
      set { _session = value; }
    }
    private int _target;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"target", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int target
    {
      get { return _target; }
      set { _target = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WorkAnt")]
  public partial class WorkAnt : global::ProtoBuf.IExtensible
  {
    public WorkAnt() {}
    
    private int _data1;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"data1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int data1
    {
      get { return _data1; }
      set { _data1 = value; }
    }
    private int _data2;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"data2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int data2
    {
      get { return _data2; }
      set { _data2 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FrequencyArea")]
  public partial class FrequencyArea : global::ProtoBuf.IExtensible
  {
    public FrequencyArea() {}
    
    private int _area;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"area", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int area
    {
      get { return _area; }
      set { _area = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Interrupted")]
  public partial class Interrupted : global::ProtoBuf.IExtensible
  {
    public Interrupted() {}
    
    private int _interrupted;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"interrupted", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int interrupted
    {
      get { return _interrupted; }
      set { _interrupted = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WorkTime")]
  public partial class WorkTime : global::ProtoBuf.IExtensible
  {
    public WorkTime() {}
    
    private int _worktime;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"worktime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int worktime
    {
      get { return _worktime; }
      set { _worktime = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"FastID")]
  public partial class FastID : global::ProtoBuf.IExtensible
  {
    public FastID() {}
    
    private bool _fastID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"fastID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool fastID
    {
      get { return _fastID; }
      set { _fastID = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"QT")]
  public partial class QT : global::ProtoBuf.IExtensible
  {
    public QT() {}
    
    private int _flag;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"flag", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int flag
    {
      get { return _flag; }
      set { _flag = value; }
    }
    private string _readdata;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"readdata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string readdata
    {
      get { return _readdata; }
      set { _readdata = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Tagfocus")]
  public partial class Tagfocus : global::ProtoBuf.IExtensible
  {
    public Tagfocus() {}
    
    private bool _tagfocus;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tagfocus", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool tagfocus
    {
      get { return _tagfocus; }
      set { _tagfocus = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Version")]
  public partial class Version : global::ProtoBuf.IExtensible
  {
    public Version() {}
    
    private string _FirmVersion;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"FirmVersion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string FirmVersion
    {
      get { return _FirmVersion; }
      set { _FirmVersion = value; }
    }
    private string _HardVersion;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"HardVersion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string HardVersion
    {
      get { return _HardVersion; }
      set { _HardVersion = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReadTag")]
  public partial class ReadTag : global::ProtoBuf.IExtensible
  {
    public ReadTag() {}
    
    private int _bank;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bank
    {
      get { return _bank; }
      set { _bank = value; }
    }
    private int _startAdd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"startAdd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int startAdd
    {
      get { return _startAdd; }
      set { _startAdd = value; }
    }
    private int _len;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"len", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int len
    {
      get { return _len; }
      set { _len = value; }
    }

    private string _password = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string password
    {
      get { return _password; }
      set { _password = value; }
    }

    private int _fliter = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"fliter", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fliter
    {
      get { return _fliter; }
      set { _fliter = value; }
    }

    private int _fliterlen = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"fliterlen", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fliterlen
    {
      get { return _fliterlen; }
      set { _fliterlen = value; }
    }

    private string _fliterdata = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"fliterdata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string fliterdata
    {
      get { return _fliterdata; }
      set { _fliterdata = value; }
    }

    private string _readdata = "";
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"readdata", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string readdata
    {
      get { return _readdata; }
      set { _readdata = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WriteTag")]
  public partial class WriteTag : global::ProtoBuf.IExtensible
  {
    public WriteTag() {}
    
    private int _bank;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bank
    {
      get { return _bank; }
      set { _bank = value; }
    }
    private int _startAdd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"startAdd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int startAdd
    {
      get { return _startAdd; }
      set { _startAdd = value; }
    }
    private int _len;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"len", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int len
    {
      get { return _len; }
      set { _len = value; }
    }

    private int _password = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int password
    {
      get { return _password; }
      set { _password = value; }
    }

    private int _fliter = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"fliter", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fliter
    {
      get { return _fliter; }
      set { _fliter = value; }
    }

    private int _fliterlen = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"fliterlen", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fliterlen
    {
      get { return _fliterlen; }
      set { _fliterlen = value; }
    }

    private int _fliterdata = default(int);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"fliterdata", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int fliterdata
    {
      get { return _fliterdata; }
      set { _fliterdata = value; }
    }

    private int _writedata = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"writedata", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int writedata
    {
      get { return _writedata; }
      set { _writedata = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"KillTag")]
  public partial class KillTag : global::ProtoBuf.IExtensible
  {
    public KillTag() {}
    
    private int _bank;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"bank", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int bank
    {
      get { return _bank; }
      set { _bank = value; }
    }
    private int _startAdd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"startAdd", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int startAdd
    {
      get { return _startAdd; }
      set { _startAdd = value; }
    }
    private int _len;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"len", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int len
    {
      get { return _len; }
      set { _len = value; }
    }
    private int _password;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"password", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int password
    {
      get { return _password; }
      set { _password = value; }
    }
    private int _fliter;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"fliter", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fliter
    {
      get { return _fliter; }
      set { _fliter = value; }
    }
    private int _fliterlen;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"fliterlen", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fliterlen
    {
      get { return _fliterlen; }
      set { _fliterlen = value; }
    }
    private int _fliterdata;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"fliterdata", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int fliterdata
    {
      get { return _fliterdata; }
      set { _fliterdata = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Wifi")]
  public partial class Wifi : global::ProtoBuf.IExtensible
  {
    public Wifi() {}
    
    private string _ssid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ssid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ssid
    {
      get { return _ssid; }
      set { _ssid = value; }
    }
    private string _pwd;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"pwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string pwd
    {
      get { return _pwd; }
      set { _pwd = value; }
    }
    private string _readerIP;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"readerIP", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string readerIP
    {
      get { return _readerIP; }
      set { _readerIP = value; }
    }
    private string _readermask;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"readermask", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string readermask
    {
      get { return _readermask; }
      set { _readermask = value; }
    }
    private string _readergw;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"readergw", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string readergw
    {
      get { return _readergw; }
      set { _readergw = value; }
    }
    private string _Serverip;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Serverip", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Serverip
    {
      get { return _Serverip; }
      set { _Serverip = value; }
    }
    private int _ServerPort;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"ServerPort", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ServerPort
    {
      get { return _ServerPort; }
      set { _ServerPort = value; }
    }
    private string _modealgorithm;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"modealgorithm", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string modealgorithm
    {
      get { return _modealgorithm; }
      set { _modealgorithm = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"SIM")]
  public partial class SIM : global::ProtoBuf.IExtensible
  {
    public SIM() {}
    
    private string _apn;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"apn", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string apn
    {
      get { return _apn; }
      set { _apn = value; }
    }
    private string _usr;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"usr", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string usr
    {
      get { return _usr; }
      set { _usr = value; }
    }
    private string _pwd;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pwd", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string pwd
    {
      get { return _pwd; }
      set { _pwd = value; }
    }
    private string _serverIP;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"serverIP", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string serverIP
    {
      get { return _serverIP; }
      set { _serverIP = value; }
    }
    private string _serverport;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"serverport", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string serverport
    {
      get { return _serverport; }
      set { _serverport = value; }
    }

    private byte[] _reserve = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"reserve", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public byte[] reserve
    {
      get { return _reserve; }
      set { _reserve = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"WorkMode")]
  public partial class WorkMode : global::ProtoBuf.IExtensible
  {
    public WorkMode() {}
    
    private int _triggertimeout;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"triggertimeout", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int triggertimeout
    {
      get { return _triggertimeout; }
      set { _triggertimeout = value; }
    }
    private bool _wiegand;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"wiegand", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool wiegand
    {
      get { return _wiegand; }
      set { _wiegand = value; }
    }
    private int _wiegand_26_34;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"wiegand_26_34", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int wiegand_26_34
    {
      get { return _wiegand_26_34; }
      set { _wiegand_26_34 = value; }
    }
    private int _workmode;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"workmode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int workmode
    {
      get { return _workmode; }
      set { _workmode = value; }
    }
    private int _starttrigger;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"starttrigger", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int starttrigger
    {
      get { return _starttrigger; }
      set { _starttrigger = value; }
    }
    private int _trigger_single_multi;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"trigger_single_multi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int trigger_single_multi
    {
      get { return _trigger_single_multi; }
      set { _trigger_single_multi = value; }
    }
    private bool _readbuzzer;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"readbuzzer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool readbuzzer
    {
      get { return _readbuzzer; }
      set { _readbuzzer = value; }
    }
    private bool _writebuzzer;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"writebuzzer", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool writebuzzer
    {
      get { return _writebuzzer; }
      set { _writebuzzer = value; }
    }
    private bool _heart;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"heart", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public bool heart
    {
      get { return _heart; }
      set { _heart = value; }
    }
    private int _flitertype;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"flitertype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int flitertype
    {
      get { return _flitertype; }
      set { _flitertype = value; }
    }
    private int _flitertime;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"flitertime", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int flitertime
    {
      get { return _flitertime; }
      set { _flitertime = value; }
    }
    private int _alarmmode;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"alarmmode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int alarmmode
    {
      get { return _alarmmode; }
      set { _alarmmode = value; }
    }
    private int _checkmode;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"checkmode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int checkmode
    {
      get { return _checkmode; }
      set { _checkmode = value; }
    }
    private int _checkdata1;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"checkdata1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int checkdata1
    {
      get { return _checkdata1; }
      set { _checkdata1 = value; }
    }
    private int _checkdata2;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"checkdata2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int checkdata2
    {
      get { return _checkdata2; }
      set { _checkdata2 = value; }
    }

    private string _mainboardhardversion = "";
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"mainboardhardversion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mainboardhardversion
    {
      get { return _mainboardhardversion; }
      set { _mainboardhardversion = value; }
    }

    private string _mainboardfirmversion = "";
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"mainboardfirmversion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string mainboardfirmversion
    {
      get { return _mainboardfirmversion; }
      set { _mainboardfirmversion = value; }
    }

    private string _modulehardversion = "";
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"modulehardversion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string modulehardversion
    {
      get { return _modulehardversion; }
      set { _modulehardversion = value; }
    }

    private string _modulefirmversion = "";
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"modulefirmversion", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string modulefirmversion
    {
      get { return _modulefirmversion; }
      set { _modulefirmversion = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Net")]
  public partial class Net : global::ProtoBuf.IExtensible
  {
    public Net() {}
    
    private string _mac;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"mac", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mac
    {
      get { return _mac; }
      set { _mac = value; }
    }
    private string _readerIP;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"readerIP", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string readerIP
    {
      get { return _readerIP; }
      set { _readerIP = value; }
    }
    private string _mask;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"mask", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string mask
    {
      get { return _mask; }
      set { _mask = value; }
    }
    private string _gateway;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"gateway", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string gateway
    {
      get { return _gateway; }
      set { _gateway = value; }
    }
    private string _dns;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"dns", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string dns
    {
      get { return _dns; }
      set { _dns = value; }
    }
    private string _serverIP;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"serverIP", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string serverIP
    {
      get { return _serverIP; }
      set { _serverIP = value; }
    }
    private int _serverport;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"serverport", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int serverport
    {
      get { return _serverport; }
      set { _serverport = value; }
    }
    private int _readerport;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"readerport", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int readerport
    {
      get { return _readerport; }
      set { _readerport = value; }
    }
    private int _more;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"more", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int more
    {
      get { return _more; }
      set { _more = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Tempreture")]
  public partial class Tempreture : global::ProtoBuf.IExtensible
  {
    public Tempreture() {}
    

    private string _tempreture = "";
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tempreture", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tempreture
    {
      get { return _tempreture; }
      set { _tempreture = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MultiEPC")]
  public partial class MultiEPC : global::ProtoBuf.IExtensible
  {
    public MultiEPC() {}
    
    private int _ant;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ant", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ant
    {
      get { return _ant; }
      set { _ant = value; }
    }
    private string _epc;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"epc", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string epc
    {
      get { return _epc; }
      set { _epc = value; }
    }
    private int _pc;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"pc", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int pc
    {
      get { return _pc; }
      set { _pc = value; }
    }
    private double _rssi;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"rssi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double rssi
    {
      get { return _rssi; }
      set { _rssi = value; }
    }

    private int _direction = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"direction", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int direction
    {
      get { return _direction; }
      set { _direction = value; }
    }
    private string _IP;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"IP", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string IP
    {
      get { return _IP; }
      set { _IP = value; }
    }
    private int _count;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private string _time;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"ReaderInfo")]
  public partial class ReaderInfo : global::ProtoBuf.IExtensible
  {
    public ReaderInfo() {}
    
    private int _save;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"save", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int save
    {
      get { return _save; }
      set { _save = value; }
    }
    private string _version;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private int _txpower;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"txpower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int txpower
    {
      get { return _txpower; }
      set { _txpower = value; }
    }
    private int _rxpower;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"rxpower", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int rxpower
    {
      get { return _rxpower; }
      set { _rxpower = value; }
    }

    private int _workstate = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"workstate", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int workstate
    {
      get { return _workstate; }
      set { _workstate = value; }
    }
    private int _channel;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"channel", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int channel
    {
      get { return _channel; }
      set { _channel = value; }
    }
    private int _tagtype;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"tagtype", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int tagtype
    {
      get { return _tagtype; }
      set { _tagtype = value; }
    }
    private int _mode;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"mode", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int mode
    {
      get { return _mode; }
      set { _mode = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MultiID")]
  public partial class MultiID : global::ProtoBuf.IExtensible
  {
    public MultiID() {}
    

    private int _tempreture = default(int);
    [global::ProtoBuf.ProtoMember(1, IsRequired = false, Name=@"tempreture", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int tempreture
    {
      get { return _tempreture; }
      set { _tempreture = value; }
    }
    private string _ID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ID
    {
      get { return _ID; }
      set { _ID = value; }
    }
    private double _rssi;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"rssi", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double rssi
    {
      get { return _rssi; }
      set { _rssi = value; }
    }

    private int _power = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"power", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int power
    {
      get { return _power; }
      set { _power = value; }
    }

    private int _remove = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"remove", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int remove
    {
      get { return _remove; }
      set { _remove = value; }
    }

    private int _battery = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"battery", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int battery
    {
      get { return _battery; }
      set { _battery = value; }
    }
    private int _count;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"count", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int count
    {
      get { return _count; }
      set { _count = value; }
    }
    private string _clientIP;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"clientIP", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string clientIP
    {
      get { return _clientIP; }
      set { _clientIP = value; }
    }
    private string _time;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string time
    {
      get { return _time; }
      set { _time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}