//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: Message.proto
// Note: requires additional types generated from: Request.proto
// Note: requires additional types generated from: Respond.proto
// Note: requires additional types generated from: Command.proto
// Note: requires additional types generated from: Other.proto
namespace hrvv
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Message")]
  public partial class Message : global::ProtoBuf.IExtensible
  {
    public Message() {}
    
    private hrvv.Message.MSG _type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public hrvv.Message.MSG type
    {
      get { return _type; }
      set { _type = value; }
    }
    private uint _sequence;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"sequence", DataFormat = global::ProtoBuf.DataFormat.FixedSize)]
    public uint sequence
    {
      get { return _sequence; }
      set { _sequence = value; }
    }

    private hrvv.Request _request = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"request", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public hrvv.Request request
    {
      get { return _request; }
      set { _request = value; }
    }

    private hrvv.Respond _respond = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"respond", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public hrvv.Respond respond
    {
      get { return _respond; }
      set { _respond = value; }
    }

    private hrvv.Command _command = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"command", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public hrvv.Command command
    {
      get { return _command; }
      set { _command = value; }
    }

    private hrvv.Other _other = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"other", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public hrvv.Other other
    {
      get { return _other; }
      set { _other = value; }
    }
    [global::ProtoBuf.ProtoContract(Name=@"MSG")]
    public enum MSG
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"REQUEST", Value=1)]
      REQUEST = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"RESPOND", Value=2)]
      RESPOND = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"COMMAND", Value=3)]
      COMMAND = 3,
            
      [global::ProtoBuf.ProtoEnum(Name=@"OTHER", Value=4)]
      OTHER = 4
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}